[package]
name = "rs-dungeon"
version = "0.1.0"
edition = "2021"
# just dependencies opt-level = 1
#[profile.dev.package."*"]
#opt-level = 1

[dependencies]
rltk = { version = "0.8.0" }
specs = { version = "0.20.0", features = ["specs-derive"] }
ggez = { version = "0.9.3" }